### PR TITLE
Try `.` instead of `text()`

### PR DESCRIPTION
**Pull request by anze3db**

### CODE REVIEW

**Comment by anze3db** [comment]
@irkonikovich I've tried changing `text()` to `.` but this breaks in some unexpected ways.

```
screen.get_by_text("Email add", exact=False)
```
now finds 5 elements in the template below, but it should only find one:
```
<body>
    <form>
        <div>
            <label for="email">Email address</label>
       </div>
    </form>
</body>
```

Any ideas how to fix it?

**Comment by irkonikovich** [comment]
> Any ideas how to fix it?

No

**Comment by anze3db** [comment]
I've added a test case for when `text()` fails, but I'm not sure how to make all the test cases pass now 😓 .

If we use `text()` then the issue is that text() only takes the text value of the first child.

If we use `.` this fixes the problem because `.` concatenates all the children, but then we can't use it with `*` since it will match on multiple levels.

I guess we could make a Dot locator, but that might be even more confusing and it still wouldn't work with `*`.  🤔

**Comment by KonradMar** [comment]
> Any ideas how to fix it?

Maybe this:

`//*[text()[contains(.,'ABC')]]`

I haven't test it but looks promising:
https://stackoverflow.com/questions/3655549/xpath-containstext-some-string-doesnt-work-when-used-with-node-with-more

**Comment by anze3db** [comment]
@KonradMar looks like it works, all the tests are green! 🎉

I'll make a new release with these changes.

**Pull request merged**
